on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to gain sum of github commits today
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: gain sum of github commits today
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          username: 'yiliang114'
      - name: Get the output sum
        run: echo "Today ${{ steps.test.inputs.username }} has committed ${{ steps.test.outputs.sum }} times."
